language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-19

    
before_script:
    - gradle -v
    - cd ActionBarCompat-ListPopupMenu

script:
    #   - gradle assembleDebug --stacktrace
    - ./gradlew assembleDebug --stacktrace

#after_success:
    #- puts "\nDone"